============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.3.3, pluggy-1.5.0
rootdir: /home/wilkinson/Documents/TCC/TG
collected 12 items

QuixBugs/python_testcases/test_lis.py ........FFFF                       [100%]

=================================== FAILURES ===================================
___________________________ test_lis[input_data8-3] ____________________________

input_data = [[4, 1, 5, 3, 7, 6, ...]], expected = 3

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_lis(input_data, expected):
>       assert lis(*input_data) == expected
E       assert 2 == 3
E        +  where 2 = lis(*[[4, 1, 5, 3, 7, 6, ...]])

QuixBugs/python_testcases/test_lis.py:15: AssertionError
___________________________ test_lis[input_data9-6] ____________________________

input_data = [[10, 22, 9, 33, 21, 50, ...]], expected = 6

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_lis(input_data, expected):
>       assert lis(*input_data) == expected
E       assert 5 == 6
E        +  where 5 = lis(*[[10, 22, 9, 33, 21, 50, ...]])

QuixBugs/python_testcases/test_lis.py:15: AssertionError
___________________________ test_lis[input_data10-3] ___________________________

input_data = [[7, 10, 9, 2, 3, 8, ...]], expected = 3

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_lis(input_data, expected):
>       assert lis(*input_data) == expected
E       assert 1 == 3
E        +  where 1 = lis(*[[7, 10, 9, 2, 3, 8, ...]])

QuixBugs/python_testcases/test_lis.py:15: AssertionError
___________________________ test_lis[input_data11-4] ___________________________

input_data = [[9, 11, 2, 13, 7, 15]], expected = 4

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_lis(input_data, expected):
>       assert lis(*input_data) == expected
E       assert 3 == 4
E        +  where 3 = lis(*[[9, 11, 2, 13, 7, 15]])

QuixBugs/python_testcases/test_lis.py:15: AssertionError
=========================== short test summary info ============================
FAILED QuixBugs/python_testcases/test_lis.py::test_lis[input_data8-3] - asser...
FAILED QuixBugs/python_testcases/test_lis.py::test_lis[input_data9-6] - asser...
FAILED QuixBugs/python_testcases/test_lis.py::test_lis[input_data10-3] - asse...
FAILED QuixBugs/python_testcases/test_lis.py::test_lis[input_data11-4] - asse...
========================= 4 failed, 8 passed in 0.04s ==========================
Different AST

Tenta resolver qualquer outra coisa
