Falha na correção

Testes falharam

tenta resolver outro parte do codigo

LOG

================================================== FAILURES ==================================================
____________________________________ test_find_in_sorted[input_data1--1] _____________________________________

input_data = [[1, 2, 3, 4, 6, 7, ...], 5], expected = -1

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_find_in_sorted(input_data, expected):
>       assert find_in_sorted(*input_data) == expected

python_testcases/test_find_in_sorted.py:15:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
python_programs/find_in_sorted.py:13: in find_in_sorted
    return binsearch(0, len(arr))
python_programs/find_in_sorted.py:9: in binsearch
    return binsearch(mid, end)
python_programs/find_in_sorted.py:7: in binsearch
    return binsearch(start, mid)
python_programs/find_in_sorted.py:7: in binsearch
    return binsearch(start, mid)
python_programs/find_in_sorted.py:9: in binsearch
    return binsearch(mid, end)
python_programs/find_in_sorted.py:9: in binsearch
    return binsearch(mid, end)
E   RecursionError: maximum recursion depth exceeded in comparison
!!! Recursion detected (same locals & position)
____________________________________ test_find_in_sorted[input_data6--1] _____________________________________

input_data = [[24, 26, 28, 50, 59], 101], expected = -1

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_find_in_sorted(input_data, expected):
>       assert find_in_sorted(*input_data) == expected

python_testcases/test_find_in_sorted.py:15:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
python_programs/find_in_sorted.py:13: in find_in_sorted
    return binsearch(0, len(arr))
python_programs/find_in_sorted.py:9: in binsearch
    return binsearch(mid, end)
python_programs/find_in_sorted.py:9: in binsearch
    return binsearch(mid, end)
python_programs/find_in_sorted.py:9: in binsearch
    return binsearch(mid, end)
python_programs/find_in_sorted.py:9: in binsearch
    return binsearch(mid, end)
python_programs/find_in_sorted.py:9: in binsearch
    return binsearch(mid, end)
E   RecursionError: maximum recursion depth exceeded in comparison
!!! Recursion detected (same locals & position)
========================================== short test summary info ===========================================
FAILED python_testcases/test_find_in_sorted.py::test_find_in_sorted[input_data1--1] - RecursionError: maximum recursion depth exceeded in comparison
FAILED python_testcases/test_find_in_sorted.py::test_find_in_sorted[input_data6--1] - RecursionError: maximum recursion depth exceeded in comparison
======================================== 2 failed, 5 passed in 0.05s =========================================
