============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.3.3, pluggy-1.5.0
rootdir: /home/wilkinson/Documents/TCC/TG
collected 7 items

QuixBugs/python_testcases/test_kth.py .F....F                            [100%]

=================================== FAILURES ===================================
___________________________ test_kth[input_data1-7] ____________________________

input_data = [[3, 6, 7, 1, 6, 3, ...], 5], expected = 7

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_kth(input_data, expected):
>       assert kth(*input_data) == expected

QuixBugs/python_testcases/test_kth.py:15: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
QuixBugs/python_programs/kth.py:13: in kth
    return kth(above, k - 1)
QuixBugs/python_programs/kth.py:13: in kth
    return kth(above, k - 1)
QuixBugs/python_programs/kth.py:13: in kth
    return kth(above, k - 1)
QuixBugs/python_programs/kth.py:13: in kth
    return kth(above, k - 1)
QuixBugs/python_programs/kth.py:13: in kth
    return kth(above, k - 1)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

arr = [], k = 0

    def kth(arr, k):
>       pivot = arr[0]
E       IndexError: list index out of range

QuixBugs/python_programs/kth.py:3: IndexError
__________________________ test_kth[input_data6-322] ___________________________

input_data = [[45, 2, 6, 8, 42, 90, ...], 6], expected = 322

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_kth(input_data, expected):
>       assert kth(*input_data) == expected

QuixBugs/python_testcases/test_kth.py:15: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
QuixBugs/python_programs/kth.py:13: in kth
    return kth(above, k - 1)
QuixBugs/python_programs/kth.py:13: in kth
    return kth(above, k - 1)
QuixBugs/python_programs/kth.py:13: in kth
    return kth(above, k - 1)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

arr = [], k = 3

    def kth(arr, k):
>       pivot = arr[0]
E       IndexError: list index out of range

QuixBugs/python_programs/kth.py:3: IndexError
=========================== short test summary info ============================
FAILED QuixBugs/python_testcases/test_kth.py::test_kth[input_data1-7] - Index...
FAILED QuixBugs/python_testcases/test_kth.py::test_kth[input_data6-322] - Ind...
========================= 2 failed, 5 passed in 0.04s ==========================
Different AST


prover soluççao mas insere bug novo
