============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.3.3, pluggy-1.5.0
rootdir: /home/wilkinson/Documents/TCC/TG
collected 5 items

QuixBugs/python_testcases/test_powerset.py FFF.F                         [100%]

=================================== FAILURES ===================================
_____________________ test_powerset[input_data0-expected0] _____________________

input_data = [['a', 'b', 'c']]
expected = [[], ['c'], ['b'], ['b', 'c'], ['a'], ['a', 'c'], ...]

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_powerset(input_data, expected):
>       assert powerset(*input_data) == expected
E       AssertionError: assert [['a', 'b', '...], ['b'], ...] == [[], ['c'], [...a', 'c'], ...]
E         
E         At index 0 diff: ['a', 'b', 'c'] != []
E         Use -v to get more diff

QuixBugs/python_testcases/test_powerset.py:15: AssertionError
_____________________ test_powerset[input_data1-expected1] _____________________

input_data = [['a', 'b']], expected = [[], ['b'], ['a'], ['a', 'b']]

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_powerset(input_data, expected):
>       assert powerset(*input_data) == expected
E       AssertionError: assert [['a', 'b'], ['a'], ['b'], []] == [[], ['b'], ['a'], ['a', 'b']]
E         
E         At index 0 diff: ['a', 'b'] != []
E         Use -v to get more diff

QuixBugs/python_testcases/test_powerset.py:15: AssertionError
_____________________ test_powerset[input_data2-expected2] _____________________

input_data = [['a']], expected = [[], ['a']]

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_powerset(input_data, expected):
>       assert powerset(*input_data) == expected
E       AssertionError: assert [['a'], []] == [[], ['a']]
E         
E         At index 0 diff: ['a'] != []
E         Use -v to get more diff

QuixBugs/python_testcases/test_powerset.py:15: AssertionError
_____________________ test_powerset[input_data4-expected4] _____________________

input_data = [['x', 'df', 'z', 'm']]
expected = [[], ['m'], ['z'], ['z', 'm'], ['df'], ['df', 'm'], ...]

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_powerset(input_data, expected):
>       assert powerset(*input_data) == expected
E       AssertionError: assert [['x', 'df', ...x', 'z'], ...] == [[], ['m'], [...f', 'm'], ...]
E         
E         At index 0 diff: ['x', 'df', 'z', 'm'] != []
E         Use -v to get more diff

QuixBugs/python_testcases/test_powerset.py:15: AssertionError
=========================== short test summary info ============================
FAILED QuixBugs/python_testcases/test_powerset.py::test_powerset[input_data0-expected0]
FAILED QuixBugs/python_testcases/test_powerset.py::test_powerset[input_data1-expected1]
FAILED QuixBugs/python_testcases/test_powerset.py::test_powerset[input_data2-expected2]
FAILED QuixBugs/python_testcases/test_powerset.py::test_powerset[input_data4-expected4]
========================= 4 failed, 1 passed in 0.04s ==========================
Different AST

falha na correção

encontra o bug, mas a correção introduz outro bug
