============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.3.3, pluggy-1.5.0
rootdir: /home/wilkinson/Documents/TCC/TG
collected 7 items

QuixBugs/python_testcases/test_find_in_sorted.py ....F..                 [100%]

=================================== FAILURES ===================================
_____________________ test_find_in_sorted[input_data4--1] ______________________

input_data = [[3, 5, 6, 7, 8, 9, ...], 0], expected = -1

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_find_in_sorted(input_data, expected):
>       assert find_in_sorted(*input_data) == expected

QuixBugs/python_testcases/test_find_in_sorted.py:15: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
QuixBugs/python_programs/find_in_sorted.py:13: in find_in_sorted
    return binsearch(0, len(arr) - 1)  # Adjust end index to avoid potential out-of-bounds
QuixBugs/python_programs/find_in_sorted.py:7: in binsearch
    return binsearch(start, mid - 1)  # Exclude mid
QuixBugs/python_programs/find_in_sorted.py:7: in binsearch
    return binsearch(start, mid - 1)  # Exclude mid
QuixBugs/python_programs/find_in_sorted.py:7: in binsearch
    return binsearch(start, mid - 1)  # Exclude mid
QuixBugs/python_programs/find_in_sorted.py:7: in binsearch
    return binsearch(start, mid - 1)  # Exclude mid
QuixBugs/python_programs/find_in_sorted.py:7: in binsearch
    return binsearch(start, mid - 1)  # Exclude mid
QuixBugs/python_programs/find_in_sorted.py:7: in binsearch
    return binsearch(start, mid - 1)  # Exclude mid
E   RecursionError: maximum recursion depth exceeded in comparison
!!! Recursion detected (same locals & position)
=========================== short test summary info ============================
FAILED QuixBugs/python_testcases/test_find_in_sorted.py::test_find_in_sorted[input_data4--1]
========================= 1 failed, 6 passed in 0.04s ==========================
Different AST

prover solução mas insere bug
