============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.3.3, pluggy-1.5.0
rootdir: /home/wilkinson/Documents/TCC/TG
collected 9 items

QuixBugs/python_testcases/test_lcs_length.py F...F..FF                   [100%]

=================================== FAILURES ===================================
________________________ test_lcs_length[input_data0-2] ________________________

input_data = ['witch', 'sandwich'], expected = 2

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_lcs_length(input_data, expected):
>       assert lcs_length(*input_data) == expected
E       AssertionError: assert 4 == 2
E        +  where 4 = lcs_length(*['witch', 'sandwich'])

QuixBugs/python_testcases/test_lcs_length.py:15: AssertionError
________________________ test_lcs_length[input_data4-3] ________________________

input_data = ['cyborg', 'cyber'], expected = 3

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_lcs_length(input_data, expected):
>       assert lcs_length(*input_data) == expected
E       AssertionError: assert 4 == 3
E        +  where 4 = lcs_length(*['cyborg', 'cyber'])

QuixBugs/python_testcases/test_lcs_length.py:15: AssertionError
________________________ test_lcs_length[input_data7-3] ________________________

input_data = ['flippy', 'floppy'], expected = 3

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_lcs_length(input_data, expected):
>       assert lcs_length(*input_data) == expected
E       AssertionError: assert 5 == 3
E        +  where 5 = lcs_length(*['flippy', 'floppy'])

QuixBugs/python_testcases/test_lcs_length.py:15: AssertionError
________________________ test_lcs_length[input_data8-3] ________________________

input_data = ['acbdegcedbg', 'begcfeubk'], expected = 3

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_lcs_length(input_data, expected):
>       assert lcs_length(*input_data) == expected
E       AssertionError: assert 6 == 3
E        +  where 6 = lcs_length(*['acbdegcedbg', 'begcfeubk'])

QuixBugs/python_testcases/test_lcs_length.py:15: AssertionError
=========================== short test summary info ============================
FAILED QuixBugs/python_testcases/test_lcs_length.py::test_lcs_length[input_data0-2]
FAILED QuixBugs/python_testcases/test_lcs_length.py::test_lcs_length[input_data4-3]
FAILED QuixBugs/python_testcases/test_lcs_length.py::test_lcs_length[input_data7-3]
FAILED QuixBugs/python_testcases/test_lcs_length.py::test_lcs_length[input_data8-3]
========================= 4 failed, 5 passed in 0.04s ==========================
Different AST

prover solução mas insere novo bug
